name: i12_into_012
description: "A simple todo app with local persistence."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3

  shared_preferences: ^2.0.0   # пакет для локального хранения
  uuid: ^4.5.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
